#magento2 user vars:
magento2_user: test-ssh
magento2_group: clp

#mysql vars:
mysql_root_user: root
mysql_magento2_db: magento2
mysql_magento2_user: magento2_user
mysql_version: "8.0"
mysql_service_name: "mysql"
mysql_config_file: "/etc/mysql/conf.d/magento2.cnf"

#php vars:
php_fpm_pool: magento2
php_version: "8.3"
varnish_port: 80

#magento2 vars:
magento2_home: /var/www/magento2
magento2_domain: test.mgt.com
composer_home: /tmp/composer
magento2_admin_firstname: Sai
magento2_admin_lastname: Krishna
magento2_admin_email: gunduboinasaikrishna@gmail.com
magento2_admin_user: testadmin
magento2_admin_password: TestAdmin@123

# Redis vars:
redis_host: "127.0.0.1"
redis_port: 6379
redis_cache_db: 0
redis_page_cache_db: 1
redis_session_db: 2
redis_password: ""

# Elasticsearch vars:
elasticsearch_version: "7.x"
elasticsearch_host: "127.0.0.1"
elasticsearch_port: 9200
elasticsearch_index_prefix: magento2

