$ANSIBLE_VAULT;1.1;AES256
63653635363364373135613330303833653336626563393530313238393361303235376537313738
6537643363383538633030343436666334633630306131660a376661303666373633643932306639
38313135393234396564383435653838386461636463633030333031623237663365626464333038
6663633131633130640a353164336437353665376133383165643236393239646631303535616261
30616236646366633034663665613738663739643132356164626262616162633465323639633366
35623765363635613535643838623035313565383736366465633864346463646431333064653732
61323261316234663661383235353862363538383239353739326366633430623333626537326466
34393533353362383765646336323561613334313238343664653961343766613830633938646637
63323631336436306637366330616163313964333934663238303232653135383864646664313163
66666334336131333938636433666336643137646237353730346132323634303361666562333931
62643935383364356232656233663162323830313032386665653664613432363963383837623531
61303333666630643661386566633661303139306166336566316566376439376237623034316634
31346437376261326163353366366563393433343735306166616438623265313530
