$ANSIBLE_VAULT;1.1;AES256
39353038383561666333613736303938373732336664353136623332663863363237303031363133
3134346162393266363239363339623734353761663733380a656639393038343764313762626563
36623636323431383539343731613463353635383936366237363132393766623933653261363363
3365343436643536640a626636313239653563386235656161643132643866373232643635333239
62663633663836353831333565623836666239626633316436366465303061336230343032663261
65316634656131616164353636303230386363376337343335313162353738656633316635353332
61343330323833343330306366353639623865616139666539303263316136613665666430396537
35353535373963663831316363373236623239373461393838313231613565366239323465363665
37346662333261346661326437643331363062616563376336313865333965316131386638313235
34616435313733303637613365306430353538636266656632643538373630333439613961333230
36343536336134653034636236663032626562316163633836336137613437376466306539626238
39373265333463333932373634666438653263303663663835393731613335376338356365333638
32366134663263356362613433656533363831333564633966613431613230323264363664303262
33343964646530313438613134386237326166396364383233623266373865623239643361373464
62306233623861396631623965663063646662386331653734656138613365356338323534306636
39363531616237633739
