---
- name: Install Varnish cache
  ansible.builtin.apt:
    name: varnish
    state: present
  notify: restart varnish

- name: Configure Varnish default.vcl
  ansible.builtin.template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
    owner: root
    group: root
    mode: '0644'
  notify: restart varnish

- name: Deploy magento2 NGINX configuration
  ansible.builtin.template:
    src: varnish.conf.j2
    dest: /etc/nginx/sites-available/varnish.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable magento2 site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/varnish.conf
    dest: /etc/nginx/sites-enabled/varnish.conf
    state: link
  notify: reload nginx  

- name: Configure systemd service for Varnish to listen on port {{ varnish_port }}
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/varnish.service
    regexp: '^ExecStart='
    line: >
      ExecStart=/usr/sbin/varnishd -a :{{ varnish_port }} -T localhost:6082
      -f /etc/varnish/default.vcl -s malloc,256m
  notify:
    - daemon-reload
    - restart varnish

- name: Ensure varnish service is running and enabled
  ansible.builtin.service:
    name: varnish
    state: started
    enabled: true

