---
# Validate & Add PHP Sury and Elasticsearch repos

- name: Ensure prerequisite packages installed for repo management
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - unzip
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
      - dnsutils
      - software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
    
# PHP Sury Repository

- name: Check if PHP Sury repo exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/php-sury.list
  register: php_repo_check

- name: Add PHP Sury GPG Key
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: not php_repo_check.stat.exists

- name: Add PHP Sury Repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    filename: php-sury
    state: present
  when: not php_repo_check.stat.exists

# Elasticsearch Repository

- name: Check if Elasticsearch repo exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/elasticsearch-{{ elasticsearch_version }}.list
  register: es_repo_check

- name: Add Elasticsearch GPG Key
  ansible.builtin.apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: not es_repo_check.stat.exists

- name: Add Elasticsearch Repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
    filename: "elasticsearch-{{ elasticsearch_version }}"
    state: present
  when: not es_repo_check.stat.exists


- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Remove any old MySQL keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings/mysql.gpg
    state: absent

- name: Import MySQL APT GPG key (from keyserver)
  ansible.builtin.shell: |
    gpg --no-default-keyring --keyring /usr/share/keyrings/mysql-temp.gpg \
        --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C
    gpg --no-default-keyring --keyring /usr/share/keyrings/mysql-temp.gpg \
        --export --output /etc/apt/keyrings/mysql.gpg
    chmod 644 /etc/apt/keyrings/mysql.gpg
  args:
    creates: /etc/apt/keyrings/mysql.gpg

- name: Add MySQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/mysql.gpg] http://repo.mysql.com/apt/debian bookworm mysql-8.0"
    state: present
    filename: mysql

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

