---
- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx user is set to magento2 user in nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^user\s+'
    line: "user {{ nginx_user }};"
    backrefs: yes
  notify: reload nginx

- name: Deploy magento2 NGINX configuration
  ansible.builtin.template:
    src: nginx_magento2.conf.j2
    dest: /etc/nginx/sites-available/magento2.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable magento2 site configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/magento2.conf
    dest: /etc/nginx/sites-enabled/magento2.conf
    state: link
  notify: reload nginx

- name: Remove default site if present
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Ensure NGINX is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

